### ISSUE TITLE
fix error on build to allow for Async vue components load

### ISSUE THREAD

**Issue by pablogiralt** [jimmylion/slate-tools#1]
When trying to build with webpack Vue components loaded async, we get this error:

```
/Users/pablo/shopify/jimmylion/node_modules/extract-text-webpack-plugin/dist/index.js:115
      let moduleSource = chunkModule.source(compilation.dependencyTemplates, compilation.runtimeTemplate);
                                     ^

TypeError: chunkModule.source is not a function
    at Function.renderExtractedChunk (/Users/pablo/shopify/jimmylion/node_modules/extract-text-webpack-plugin/dist/index.js:115:38)
    at ExtractTextPlugin.extractedChunks.forEach.extractedChunk (/Users/pablo/shopify/jimmylion/node_modules/extract-text-webpack-plugin/dist/index.js:313:46)
    at Array.forEach (<anonymous>)
    at compilation.hooks.additionalAssets.tapAsync.assetCb (/Users/pablo/shopify/jimmylion/node_modules/extract-text-webpack-plugin/dist/index.js:301:25)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pablo/shopify/jimmylion/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/pablo/shopify/jimmylion/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (/Users/pablo/shopify/jimmylion/node_modules/webpack/lib/Compilation.js:1277:32)
    at _err0 (eval at create (/Users/pablo/shopify/jimmylion/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)
    at _async2.default.forEach.err (/Users/pablo/shopify/jimmylion/node_modules/extract-text-webpack-plugin/dist/index.js:296:11)
    at /Users/pablo/shopify/jimmylion/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/pablo/shopify/jimmylion/node_modules/async/dist/async.js:1064:13)
    at /Users/pablo/shopify/jimmylion/node_modules/async/dist/async.js:969:16
    at _async2.default.forEach.err (/Users/pablo/shopify/jimmylion/node_modules/extract-text-webpack-plugin/dist/index.js:274:13)
    at /Users/pablo/shopify/jimmylion/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/pablo/shopify/jimmylion/node_modules/async/dist/async.js:1064:13)
    at /Users/pablo/shopify/jimmylion/node_modules/async/dist/async.js:969:16
    at compilation.rebuildModule.err (/Users/pablo/shopify/jimmylion/node_modules/extract-text-webpack-plugin/dist/index.js:261:26)
    at callback (/Users/pablo/shopify/jimmylion/node_modules/webpack/lib/Compilation.js:1103:5)
    at processModuleDependencies.err (/Users/pablo/shopify/jimmylion/node_modules/webpack/lib/Compilation.js:1126:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error Command failed with exit code 1.
```

**Comment by pablogiralt** [comment]
this is needed for https://github.com/jimmylion/shopify-theme/issues/128
